jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: notification
  datasource:
    url: ENC(Qq9ATFy73X5gQv1K4tlmYqpjBcQBI8C96Xv4UCBt+n55/0WfLybe2QNDTvxTNr1XbFMmO07sqMa0Pd5iR6Dh7g1EIAJTabqyLySKnjbxRlk=)
    username: ENC(XhGT41xwg0J9hSXkV9tPjQ==)
    password: ENC(cOWaniGDoCFEXR9v+wRBVEwsJ5Hg6vQN)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.ByteArrayDeserializer
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="nl8P18Py3g";
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      transaction-status: transaction-status

auth:
  service:
    url: http://auth-service.auth:8888